### ISSUE TITLE
document or add example of generating rsa key

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_JWT#12]
the example in this repo expects a `secrets["private_key"]` value but I couldn't find any mention of the correct format in this repo. 

There is a learn guide page here: https://learn.adafruit.com/pyportal-iot-plant-monitor-with-google-cloud-iot-core-and-circuitpython/code-setup#creating-a-rsa-key-pair-3038069-14 that shows how to generate this key and put it into secrets in the expected format. 

It would be great to include documentation and/or a pointer to this guide page so folks can find the right format to use more easily.

**Comment by ranaya-formant** [comment]
I experienced the same proble

**Comment by Neradoc** [comment]
Ah ! I was stumped by that too when trying to understand somebody's issue on discord.
The type hint is wrong too: `Optional[str]`.
It would be nice if the example included the key in the right format, or an example `jwt_simpletest_secrets.py` file.

**Comment by tekktrik** [comment]
I can submit a PR for the type hint and associated docstring at least,

**Comment by ladyada** [comment]
@tekktrik @FoamyGuy @Neradoc can one of ya'll also submit a test example? do you need help creating it?

**Comment by tekktrik** [comment]
I can make a test when I PR the documentation change, I can let you know if I hit issues!

**Comment by tekktrik** [comment]
@ladyada anything in particular I should write a test for?  Or did you mean write a specific example of a `simpletest`?

**Comment by tekktrik** [comment]
Hey @ladyada just hoping you can clarify whether you meant a simpletest example of a pytest (or equivalent) test?
